# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseURL = "https://luizmacedo.dev" # Include trailing slash
languageCode = "en-us"
title = "Luiz Macedo's Blog"
author = "Luiz Macedo"
copyright = "Copyright © 2020, Luiz Macedo; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = "luiz-macedo-blog" # Comments

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false
    noClasses = false
    # style = "monokai"
    tabWidth = 2

[params]
copyrightHolder = "Luiz Fernando de Macedo"
author = "Luiz Macedo"
twitter = "@OLuizMacedo"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "DevOps Support Escalation Engineer at Microsoft. I code, write, speak, empower, promote, learn and listen. Opinions are my own."

# github = "https://github.com/LuizMacedo" # https://github.com/LuizMacedo
# linkedin = "https://www.linkedin.com/in/luizfmacedo" # https://www.linkedin.com/in/luizfmacedo/
# email = "luizmacedo@outlook.com" # luizmacedo@outlook.com
# instagram = "https://www.instagram.com/oluizmacedo" # https://www.instagram.com/oluizmacedo/

# Google analytics Id
ga_analytics = "UA-82328117-4"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png" 

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false 


# directory(s) where your articles are located
mainSections = ["posts"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

#logo = "images/Logo.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'