# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseURL = "https://luizmacedo.dev" # Include trailing slash
languageCode = "en-us"
# title = "Luiz Macedo"
author = "Luiz Macedo"
copyright = "Copyright © 2020 LUIZ MACEDO'S BLOG is licensed under CC BY 4.0"
canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = "luizmacedo-dev" # Comments
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
# disableLanguages = ["fr", "ja"]

# [Taxonomies]
#   tag = "tags"
#   categories = "categories"

# [blackfriday]
#   angledQuotes = true
#   hrefTargetBlank = true

[languages]
  [languages.en]
    contentDir = "content/english" #English
    languageName = "English" # Name shown in the main menu
    title = "Luiz Macedo"
    weight = 0

    # You can configure the theme parameter for each language.     
    [languages.en.params]
        linkedin = "https://www.linkedin.com/in/luizfmacedo/"
        author = "Luiz Macedo "
        info = "DevOps Engineer"
        #description = "John Doe's personal website" <- quick description
        keywords = "blog,developer,personal, devops"

    [languages.en.menu]
        [[languages.en.menu.main]]
            name = "Home"
            url = ""
            weight = 1
        [[languages.en.menu.main]]
            name = "About"
            url = "/pages/about/"
            weight = 2
        # [[languages.en.menu.main]]
        #     name = "Tags"
        #     url = "/tags/"
        #     weight = 3
  [languages.br]
    contentDir = "content/portuguese"
    languageName = "Português" # Name shown in the main menu
    title = "Luiz Macedo"
    weight = 10
    
    [languages.br.params]
        linkedin = "https://www.linkedin.com/in/luizfmacedo/"
        author = "Luiz Macedo "
        info = "DevOps Engineer"
        #description = "John Doe's personal website" <- quick description
        keywords = "blog,developer,personal, devops"
        introDescription = "Eu sou DevOps Support Escalation Engineer na Microsoft. Eu crio código, escrevo livros, palestro, empodero pessoas, promovo eventos, aprendo e ouço. Opinions are my own."

        [[languages.br.menu.main]]
            name = "Início"
            url = ""
            weight = 1
        [[languages.br.menu.main]]
            name = "Sobre"
            url = "/pages/sobre/"
            weight = 2
        # [[languages.br.menu.main]]
        #     name = "Tags"
        #     url = "/tags/"
        #     weight = 3
    [languages.br.Taxonomies]
        tag = "tags"
        categories = "categorias"
                
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false
    noClasses = false
    # style = "monokai"
    tabWidth = 2

[params]
copyrightHolder = "Luiz Fernando de Macedo"
author = "Luiz Macedo"
twitter = "@OLuizMacedo"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "I’m Luiz Macedo - a proud father, loving husband, and passionate tech and creative professional. Opinions are my own."

# Google analytics Id
ga_analytics = "UA-82328117-4"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "/logos/Asset 6.png" 

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false 


# directory(s) where your articles are located
mainSections = ["posts"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

logo = "/logos/Menu.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'