# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Deploy Hugo Public to GitHub Pages
      run: | 
        #!/bin/sh
        
        # If a command fails then the deploy stops
        set -e

        printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"

        # Build the project.
        hugo # if using a theme, replace with `hugo -t <YOURTHEME>`

        # Go To Public folder
        cd public

        # Add changes to git.
        git add .

        # Commit changes.
        msg="rebuilding site $(date)"
        if [ -n "$*" ]; then
          msg="$*"
        fi
        git commit -m "$msg"

        # Push source and build repos.
        git push origin master
